from __future__ import annotations

from dataclasses import dataclass, asdict
from pathlib import Path
import re


@dataclass
class CleanReport:
    source_path: str
    output_path: str | None
    original_chars: int
    cleaned_chars: int
    removed_chars: int
    removed_images: int
    removed_anchors: int
    removed_div_fences: int
    removed_raw_html_blocks: int
    removed_span_attributes: int
    normalised_headings: int
    dropped_front_matter: bool


FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
IMAGE_RE = re.compile(r"!\[[^\]]*\]\([^\)]*\)(?:\{[^}]*\})?")
EMPTY_ANCHOR_RE = re.compile(r"\[\]\{#[^}]+\}")
SPAN_ATTR_RE = re.compile(r"\[([^\[\]]*?)\]\{[^}]*\}")
RAW_ATTR_RE = re.compile(r"\{=[a-zA-Z0-9_-]+\}")
HTML_TAG_RE = re.compile(r"</?[^>]+>")
DIV_FENCE_LINE_RE = re.compile(r"^\s*:{3,}.*$", re.MULTILINE)
HR_RE = re.compile(r"^\s*(?:-{5,}|_{5,}|\*{5,})\s*$", re.MULTILINE)
IDGEN_LINE_RE = re.compile(r"^\s*(?:_idGen|\. _idGen|#HtFa|HtFa|\{#HtFa).*?$", re.MULTILINE)
SVG_BLOCK_RE = re.compile(r":::.*?\n\s*<svg\b.*?</svg>\s*\n:::\s*", re.DOTALL | re.IGNORECASE)
HTML_BLOCK_RE = re.compile(r"<svg\b.*?</svg>", re.DOTALL | re.IGNORECASE)
FOOTNOTE_LINK_RE = re.compile(r"\[+([*†‡§¶#0-9,\- ]+)\]+\([^\)]*footnote[^\)]*\)(?:\{[^}]*\})?")
MARKDOWN_LINK_RE = re.compile(r"\[([^\]]+)\]\(([^\)]*)\)")
MULTI_BLANK_RE = re.compile(r"\n{3,}")

# Chapter headings commonly produced by EPUB-to-Markdown conversion.
CHAPTER_NUM_RE = re.compile(r"^Chapter\s+(\d+|[IVXLCDM]+)\s*$", re.IGNORECASE)

# Common front-matter headings that are worth keeping as content.
CONTENT_START_RE = re.compile(
    r"^(?:Preface(?:\s+to\s+the\s+.+)?|Introduction|Prologue|Chapter\s+\d+|Chapter\s+[IVXLCDM]+)\s*$",
    re.IGNORECASE,
)


def _strip_yaml_frontmatter(text: str) -> tuple[str | None, str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None, text
    return match.group(0), text[match.end():]


def _restore_yaml_frontmatter(frontmatter: str | None, body: str) -> str:
    if not frontmatter:
        return body
    return frontmatter.rstrip() + "\n\n" + body.lstrip()


def _drop_pre_content_matter(text: str) -> tuple[str, bool]:
    """Drop cover/copyright/catalogue/promotional material before real reading content."""
    lines = text.splitlines()
    for idx, line in enumerate(lines):
        candidate = line.strip()
        if idx + 1 < len(lines):
            candidate_two_lines = f"{candidate} {lines[idx + 1].strip()}".strip()
        else:
            candidate_two_lines = candidate
        if CONTENT_START_RE.match(candidate) or CONTENT_START_RE.match(candidate_two_lines):
            return "\n".join(lines[idx:]), idx > 0
    return text, False


def _normalise_pandoc_spans(text: str) -> tuple[str, int]:
    count = 0
    previous = None
    while previous != text:
        previous = text
        text, n = SPAN_ATTR_RE.subn(lambda m: m.group(1), text)
        count += n
    return text, count


def _remove_raw_blocks(text: str) -> tuple[str, int]:
    text, n1 = SVG_BLOCK_RE.subn("\n", text)
    text, n2 = HTML_BLOCK_RE.subn("\n", text)
    return text, n1 + n2


def _remove_visual_noise(text: str) -> tuple[str, dict[str, int]]:
    stats = {
        "removed_raw_html_blocks": 0,
        "removed_images": 0,
        "removed_anchors": 0,
        "removed_div_fences": 0,
        "removed_span_attributes": 0,
    }

    text, stats["removed_raw_html_blocks"] = _remove_raw_blocks(text)
    text, stats["removed_images"] = IMAGE_RE.subn("", text)
    text, stats["removed_anchors"] = EMPTY_ANCHOR_RE.subn("", text)
    text, stats["removed_div_fences"] = DIV_FENCE_LINE_RE.subn("", text)
    text, n = _normalise_pandoc_spans(text)
    stats["removed_span_attributes"] = n

    # Footnote backlinks generated by EPUB conversion are retrieval noise.
    text = FOOTNOTE_LINK_RE.sub(lambda m: m.group(1).strip(), text)

    # Keep ordinary link text but remove link targets. Book content usually matters more than EPUB hrefs.
    text = MARKDOWN_LINK_RE.sub(lambda m: m.group(1), text)

    text = RAW_ATTR_RE.sub("", text)
    text = HTML_TAG_RE.sub("", text)
    text = HR_RE.sub("", text)
    text = IDGEN_LINE_RE.sub("", text)
    return text, stats


def _strip_inline_markdown_noise(text: str) -> str:
    # Remove common EPUB/Pandoc escaped clutter while preserving useful punctuation.
    text = text.replace("\u00a0", " ")
    text = text.replace("\\|", "|")
    text = text.replace("\\$", "$")
    text = text.replace("\\@", "@")
    text = text.replace("\\--", "--")
    text = text.replace("---", "—")
    text = re.sub(r"\{\.[^}]+\}", "", text)
    text = re.sub(r"\{#[^}]+\}", "", text)
    return text


def _join_wrapped_lines(text: str) -> str:
    """Convert hard-wrapped ebook paragraphs into normal paragraphs.

    Blank lines and headings/lists remain as structural boundaries.
    """
    out: list[str] = []
    para: list[str] = []

    def flush() -> None:
        nonlocal para
        if para:
            out.append(_join_paragraph_lines(para))
            para = []

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            flush()
            continue

        if _is_structural_line(line):
            flush()
            out.append(line)
            continue

        para.append(line)

    flush()
    return "\n\n".join(out)


def _is_structural_line(line: str) -> bool:
    if line.startswith("#"):
        return True
    if re.match(r"^[-*+]\s+", line):
        return True
    if re.match(r"^\d+[.)]\s+", line):
        return True
    if CHAPTER_NUM_RE.match(line):
        return True
    if CONTENT_START_RE.match(line):
        return True
    return False


def _join_paragraph_lines(lines: list[str]) -> str:
    text = ""
    for line in lines:
        if not text:
            text = line
            continue
        # EPUB conversions usually hard-wrap ordinary prose. Use spaces between
        # lines; most true mid-word splits have already been repaired when inline
        # span attributes were removed.
        text += " " + line
    return re.sub(r"\s+", " ", text).strip()


def _normalise_headings(text: str) -> tuple[str, int]:
    lines = text.splitlines()
    out: list[str] = []
    changed = 0
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        next_line = lines[i + 1].strip() if i + 1 < len(lines) else ""

        chapter_match = CHAPTER_NUM_RE.match(line)
        if chapter_match:
            if next_line and not _is_structural_line(next_line):
                out.append(f"## Chapter {chapter_match.group(1)}: {next_line}")
                changed += 1
                i += 2
                continue
            out.append(f"## Chapter {chapter_match.group(1)}")
            changed += 1
            i += 1
            continue

        combined = f"{line} {next_line}".strip() if next_line else line
        if CONTENT_START_RE.match(combined) and not line.startswith("#"):
            out.append(f"# {combined}")
            changed += 1
            i += 2 if next_line and combined != line else 1
            continue

        if CONTENT_START_RE.match(line) and not line.startswith("#"):
            out.append(f"# {line}")
            changed += 1
            i += 1
            continue

        out.append(lines[i].rstrip())
        i += 1

    return "\n".join(out), changed


def _final_tidy(text: str) -> str:
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n[ \t]+", "\n", text)
    text = MULTI_BLANK_RE.sub("\n\n", text)
    return text.strip() + "\n"


def clean_markdown_text(text: str, drop_front_matter: bool = True) -> tuple[str, dict[str, int | bool]]:
    original_len = len(text)
    frontmatter, body = _strip_yaml_frontmatter(text)

    body, raw_block_count = _remove_raw_blocks(body)
    body, stats = _remove_visual_noise(body)
    stats["removed_raw_html_blocks"] += raw_block_count
    body = _strip_inline_markdown_noise(body)

    dropped = False
    if drop_front_matter:
        body, dropped = _drop_pre_content_matter(body)

    body = _join_wrapped_lines(body)
    body, heading_count = _normalise_headings(body)
    body = _final_tidy(body)
    cleaned = _restore_yaml_frontmatter(frontmatter, body)

    stats["normalised_headings"] = heading_count
    stats["dropped_front_matter"] = dropped
    stats["original_chars"] = original_len
    stats["cleaned_chars"] = len(cleaned)
    stats["removed_chars"] = max(0, original_len - len(cleaned))
    return cleaned, stats


def clean_markdown_file(
    source_path: Path,
    output_path: Path | None = None,
    in_place: bool = False,
    drop_front_matter: bool = True,
) -> CleanReport:
    if in_place and output_path is not None:
        raise ValueError("Use either output_path or in_place, not both")

    original = source_path.read_text(encoding="utf-8", errors="replace")
    cleaned, stats = clean_markdown_text(original, drop_front_matter=drop_front_matter)

    destination: Path | None = None
    if in_place:
        destination = source_path
    elif output_path is not None:
        destination = output_path

    if destination is not None:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(cleaned, encoding="utf-8")

    return CleanReport(
        source_path=str(source_path),
        output_path=str(destination) if destination else None,
        original_chars=int(stats["original_chars"]),
        cleaned_chars=int(stats["cleaned_chars"]),
        removed_chars=int(stats["removed_chars"]),
        removed_images=int(stats["removed_images"]),
        removed_anchors=int(stats["removed_anchors"]),
        removed_div_fences=int(stats["removed_div_fences"]),
        removed_raw_html_blocks=int(stats["removed_raw_html_blocks"]),
        removed_span_attributes=int(stats["removed_span_attributes"]),
        normalised_headings=int(stats["normalised_headings"]),
        dropped_front_matter=bool(stats["dropped_front_matter"]),
    )


def report_as_dict(report: CleanReport) -> dict[str, object]:
    return asdict(report)
